# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vfYceCnRUl7o1m4VhJqiD_y7ZXErXZn9
"""

import math as m
import numpy as np
import matplotlib.pyplot as plt
import plotly.figure_factory as ff
from numpy.linalg import eig
from sympy.solvers import solve
from sympy import Symbol
from scipy import integrate

"""## Parámetros de los ejercicios 5 y 6

"""

V = 0
R = 1.2#2000
C = 18#2*(10)**(-7)
L = 4.7#1.5

"""## Matriz del sistema, y sus valores y vectores propios"""

Y = np.array([[-R/L, -1/L],
              [1/C, 0]])

v,e = eig(Y)

print("Valores propios: \n" , v, "\n")
print("Vectores propios: \n" , e)

"""## Gráfica plano fase"""

x = np.linspace(-40, 40, 30)
y = np.linspace(-20, 20, 30)

Y, X = np.meshgrid(x, y)

i = -(R/L)*X -(1/L)*Y + V/L
Vc = (1/C)*X 

# Create streamline figure
fig = ff.create_streamline(x, y, i, Vc, arrow_scale=.8, 
                           name='Plano Fase')
fig.show()

