% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Taller6AED},
  pdfauthor={David Alsina, Estefanía Laverda, María Fernanda Palacio},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Taller6AED}
\author{David Alsina, Estefanía Laverda, María Fernanda Palacio}
\date{4/29/2022}

\begin{document}
\maketitle

\hypertarget{considere-la-matriz-de-covarianza-para-el-vector-aleatorio-x}{%
\subsection{1. considere la matriz de covarianza para el vector
aleatorio
X}\label{considere-la-matriz-de-covarianza-para-el-vector-aleatorio-x}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sigma11 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{0}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{Sigma22 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{))}
\NormalTok{Sigma12 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.95}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Values of U}
\NormalTok{newMatrix1}\OtherTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}\SpecialCharTok{\%*\%}\NormalTok{Sigma12}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(Sigma22)}\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(Sigma12)}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\NormalTok{eigenvectors1}\OtherTok{=} \FunctionTok{eigen}\NormalTok{(newMatrix1)}\SpecialCharTok{$}\NormalTok{vectors}

\NormalTok{newMatrix1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]   [,2]
## [1,]    0 0.0000
## [2,]    0 0.9025
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a1 }\OtherTok{=}\NormalTok{ eigenvectors1[,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\NormalTok{a2 }\OtherTok{=}\NormalTok{ eigenvectors1[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(a1,a2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  0.0  1.0 -0.1  0.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Values of V}
\NormalTok{newMatrix2}\OtherTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(Sigma12)}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(Sigma11)}\SpecialCharTok{\%*\%}\NormalTok{Sigma12}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\NormalTok{eigenvectors2 }\OtherTok{=} \FunctionTok{eigen}\NormalTok{(newMatrix2)}\SpecialCharTok{$}\NormalTok{vectors}

\NormalTok{b1 }\OtherTok{=}\NormalTok{ eigenvectors2[,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\NormalTok{b2 }\OtherTok{=}\NormalTok{ eigenvectors2[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(b1,b2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.0  0.0  0.0 -0.1
\end{verbatim}

Luego las variables canónicas son

\(U = X_2^{(1)}-0.1X_1^{(2)}\)

y

\(V = -X_1^{(1)}-0.1X_2^{(2)}\)

Ahora se calculan las correlaciones canónicas

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr1 }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{eigen}\NormalTok{(newMatrix1)}\SpecialCharTok{$}\NormalTok{values)}

\FunctionTok{print}\NormalTok{(corr1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.95 0.00
\end{verbatim}

Luego \(U_1\) tiene una correlación de 0.95 con \(V_1\) y \(U_2\) tiene
una correlación de 0.00 con \(V_2\).

\hypertarget{considere-el-vecto-aleatorio-con-media-mu-y-covarianza-sigma}{%
\subsection{\texorpdfstring{2. considere el vecto aleatorio con media
\(\mu\) y covarianza
\(\Sigma\)}{2. considere el vecto aleatorio con media \textbackslash mu y covarianza \textbackslash Sigma}}\label{considere-el-vecto-aleatorio-con-media-mu-y-covarianza-sigma}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Sigma11 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{2}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{5}\NormalTok{))}
\NormalTok{Sigma22 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{6}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{,}\DecValTok{7}\NormalTok{))}
\NormalTok{Sigma12 }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Values of U}
\NormalTok{newMatrix1}\OtherTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}\SpecialCharTok{\%*\%}\NormalTok{Sigma12}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(Sigma22)}\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(Sigma12)}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\NormalTok{eigenvectors1}\OtherTok{=} \FunctionTok{eigen}\NormalTok{(newMatrix1)}\SpecialCharTok{$}\NormalTok{vectors}

\NormalTok{a1 }\OtherTok{=}\NormalTok{ eigenvectors1[,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\NormalTok{a2 }\OtherTok{=}\NormalTok{ eigenvectors1[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma11))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(a1,a2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.3168206  0.3622269 -0.1962489 -0.3016851
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Values of V}
\NormalTok{newMatrix2}\OtherTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}\SpecialCharTok{\%*\%}\FunctionTok{t}\NormalTok{(Sigma12)}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(Sigma11)}\SpecialCharTok{\%*\%}\NormalTok{Sigma12}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\NormalTok{eigenvectors2 }\OtherTok{=} \FunctionTok{eigen}\NormalTok{(newMatrix2)}\SpecialCharTok{$}\NormalTok{vectors}

\NormalTok{b1 }\OtherTok{=}\NormalTok{ eigenvectors2[,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\NormalTok{b2 }\OtherTok{=}\NormalTok{ eigenvectors2[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{\%*\%}\FunctionTok{solve}\NormalTok{(}\FunctionTok{sqrtm}\NormalTok{(Sigma22))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(b1,b2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.36470579  0.09506271 -0.22627464 -0.38582097
\end{verbatim}

Luego las variables canónicas son

\(U = -0.3168206^{(1)} +0.3622269X_2^{(1)}-0.1962489^{(2)}-0.3016851X_2^{(2)}\)

y

\(V = -0.36470579X_1^{(1)} +0.09506271X_2^{(1)}-0.22627464X_1^{(2)}-0.38582097X_2^{(2)}\)

Ahora se calculan las correlaciones canónicas

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr1 }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{eigen}\NormalTok{(newMatrix1)}\SpecialCharTok{$}\NormalTok{values)}

\FunctionTok{print}\NormalTok{(corr1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5519301 0.4898610
\end{verbatim}

Luego \(U_1\) tiene una correlación de 0.5519301 con \(V_1\) y \(U_2\)
tiene una correlación de 0.4898610 con \(V_2\).

\end{document}
